=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmlTestxsl/sinhvienschema.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="listSV">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sinhvien" maxOccur="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                             <xs:element name="MaSV" type="xs:string"></xs:element>
                 
                <xs:element name="Hoten" type="xs:string"></xs:element>
                  
                 <xs:element name="gioitinh">
                      <xs:simpleType>
                          <xs:restriction base="xs:string">
                              <xs:pattern value="nam|nu"/>  
                              </xs:restriction>
                              </xs:simpleType>
                  </xs:element>
                  
                <xs:element name="NgaySinh" type="xs:string">
                </xs:element>
                
              <xs:element name="MaLop">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[a-zA-Z]{4}[0-9]{2}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>



                        </xs:sequence>
                    </xs:complexType>
                    
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmlTestxsl/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<?xml-stylesheet type="text/xsl" href="sinhvien.xsl"?>

<listSV
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='sinhvienschema.xsd'>
    <Sinhvien>
        <MaSV>sv001</MaSV>
        <Hoten>Nguyễn văn A</Hoten>
        <gioitinh>Nam</gioitinh>
        <NgaySinh>03/03/1992</NgaySinh>
        <MaLop>CDT2004</MaLop>
    </Sinhvien>
    <Sinhvien>
        <MaSV>sv00M</MaSV>
        <Hoten>lady</Hoten>
        <gioitinh>Nu</gioitinh>
        <NgaySinh>03/11/1997</NgaySinh>
        <MaLop>CEE123</MaLop>
    </Sinhvien>
</listSV>
