=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmlfootball/football.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="listFB">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="football" maxOccur="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                               <xs:element name="san" type="xs:string"></xs:element>
                                  <xs:element name="ngay" type="xs:date"></xs:element>
                                     <xs:element name="doi1" type="xs:string"></xs:element>
                                        <xs:element name="soBT1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:maxInclusive value="0"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                           <xs:element name="doi2" type="xs:string"></xs:element>
                                              <xs:element name="soBT2">
                                                  <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:maxInclusive value="0"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                              </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmlfootball/football.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<listFB
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='football.xsd'>
    <football>
        <san>Thống nhất</san>
        <ngay>2008-08-23</ngay>
        <doi1>SLNA</doi1>
        <soBT1>9</soBT1>
        <doi2>CSG</doi2>
        <soBT2>9</soBT2>
    </football>
 <football>
        <san>Bình Định</san>
        <ngay>2008-08-24</ngay>
        <doi1>HAGL</doi1>
        <soBT1>1</soBT1>
        <doi2>BD</doi2>
        <soBT2>4</soBT2>
    </football>
     <football>
        <san>Vinh</san>
        <ngay>2008-08-25</ngay>
        <doi1>GDT</doi1>
        <soBT1>2</soBT1>
        <doi2>NCD</doi2>
        <soBT2>2</soBT2>
    </football>
     <football>
        <san>Nam Định</san>
        <ngay>2008-08-26</ngay>
        <doi1>SLNA</doi1>
        <soBT1>7</soBT1>
        <doi2>NHACB</doi2>
        <soBT2>4</soBT2>
    </football>
</listFB>
