=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmltest3/house.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/emptyDTD.dtd to edit this template
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT Houses (house*)> <!-- ? :0 hoặc 1, * :0 hoặc nhiếu, + :1 hoặc nhiều -->
<!ELEMENT house (room+)>
<!ELEMENT room  (dimensions, windows, furniture*)>
<!ELEMENT dimensions (width, length)>
<!ELEMENT windows (window*)>
<!ELEMENT window  (elevation, width, height)>
<!ELEMENT furniture (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT elevation EMPTY>
<!ATTLIST  room name  ID #REQUIRED
            colour IDREF #IMPLIED>
<!ATTLIST  elevation facing(north | south | east | west) #REQUIRED>

=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmltest3/house.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<?xml-stylesheet type="text/css" href="house.css"?>
<!DOCTYPE Houses SYSTEM 'house.dtd'>


<Houses>
    <house>
        <room>
            <dimensions>
                <width> 21  ms </width>
                <length>23 ms </length>
            </dimensions>
            <windows>
                <window>
                    <width> 14 </width>
                    <elevation> north </elevation>
                    <height> 12 </height>
                </window>
            </windows>
            <furniture>2 </furniture>
        </room>
    </house>
</Houses>
