=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmltest4/contact.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/emptyDTD.dtd to edit this template
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT Constacts (contact*)> <!-- ? :0 hoặc 1, * :0 hoặc nhiếu, + :1 hoặc nhiều -->
<!ELEMENT contact (user+)>
<!ELEMENT user  (userdetail+, phone+, email)>
<!ELEMENT userdetail (name, adress, city)>
<!ELEMENT phone (telephone, mobile)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT adress (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ATTLIST  contact name  ID #REQUIRED
            colour IDREF #IMPLIED>

=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmltest4/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<?xml-stylesheet type="text/css" href="contact.css"?>
<!DOCTYPE Constacts SYSTEM 'contact.dtd'>


<Constacts>
    <contact>
        <user>
            <userdetail>
                <name> Frank Rizzo</name>
                <adress>1 212  W  304th Street</adress>
                <city>New york, New york 10011</city>
            </userdetail>
            <phone>
                <telephone>222-555-1212</telephone>
                <mobile> 212-555-1151 </mobile>
            </phone>
            <email> frank.rizzo@franksratchetco.com </email>
        </user>
    </contact>
</Constacts>
