=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmltest02/Orders.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/emptyDTD.dtd to edit this template
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT Orders (Order*)> <!-- ? :0 hoặc 1, * :0 hoặc nhiếu, + :1 hoặc nhiều -->
<!ELEMENT Order (OrderNo,OrderDate,CustomerName, Detail+)>
<!ELEMENT OrderNo (#PCDATA)>
<!ELEMENT OrderDate (#PCDATA)>
<!ELEMENT CustomerName (#PCDATA)>
<!ELEMENT Detail (ItemNo, ItemName, Quantity, Price)>
<!ELEMENT ItemNo (#PCDATA)>
<!ELEMENT ItemName (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ATTLIST Book Code CDATA "1">
<!ATTLIST  OrderNo  ID #REQUIRED>
<!ATTLIST  Quantity CDATA "1">
<!ATTLIST  Price CDATA "0">

=== NCanhhieu/T2207E-Diagram/xml-test01/src/xmltest02/Orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE root SYSTEM 'Orders.dtd'>
<Order>
    <OrderNo>1</OrderNo>
    <OrderDate>22/2/2022</OrderDate>
    <CustomerName>Anderw</CustomerName>
    <Detail>
        <ItemNo>123</ItemNo>
        <ItemName>Book of law</ItemName>
        <Quantity> 1</Quantity>
        <Price>20$ </Price>    
    </Detail>
</Order>
